### ISSUE TITLE
Facesmash creates sequential matches that have the same candidate in it

### ISSUE THREAD

**Issue by tko22** [hack4impact-uiuc/h4i-recruitment#95]
to reproduce:
- click through facemash a couple times
- you should see the same candidate pop up

It may be due to how we choose the candidates, in where we pick a random candidate from list a candidates with a min amount of matches with **mongo**. Maybe not use mongo to do the random picking?

A candidate needs to get up to around 10 matches before the generated matches stop having the same candidate.

**Comment by angadgarg25** [comment]
Issue with not migrating data, fixed by migrating. Since mongo does not automatically migrate upon schema changes, old documents aren't properly updated with new fields. Even if you can see the default values in the new fields when printing out the data, it may not be a part of the object. This may be something we should watch out for in the future.
